### ISSUE TITLE
Nokia Store support for Nokia X devices

### ISSUE THREAD

**Issue by Marneus68** [soomla/android-store#48]
Hi, I'm attempting to modify this project in order to use it on Nokia X devices. Up to now I figured that I have to create a new _billing provider plugin_ based on [this one made for Google Play](https://github.com/soomla/android-store-google-play), so that's what i did [here](https://github.com/Marneus68/android-store-nokia-store) for the Nokia Store billing.

The problem is that I don't really understand the building process used by this project. For now, I'm manually putting the billing provider in a fresh clone of the android-store project, fixing some import and changing the calls to GooglePlayIabService by calls to my new NokiaStoreIabService, however, once I did all that, I end up with a valid project (it doesn't show any error in Eclipse ADT) and I don't know how I'm supposed to get a .jar that I can then use with Soomla For Unity.

Is there any more detailed documentation on the building process that I haven't come across, or can anyone help me making Soomla available on the Nokia X platform ?

**Comment by refaelos** [comment]
@Marneus68 did you have any progress with this? We'd love to get the nokia plugin integrated into unity3d-store and for that we need it working with the latest version of android-store.

**Comment by Marneus68** [comment]
Hey man,

Sorry for the delay. I'm working on a lot of things for my company at the
moment.
As you may have learned form outside sources, the NokiaX project as it was
has been phased out by Microsoft. My NokiaX plugin was functionnal however
thet changed their billing API to something handled by Opera. I haven't had
the time to take a look at but I sure plan to...

I think it would be a good idea to close the feature request and open a new
one to handle the Opera stuff... I'll probably get around to it at some
point but I can't promise anything.

2015-04-08 14:35 GMT+02:00 Refael Dakar <notifications@github.com>:

> @Marneus68 <https://github.com/Marneus68> did you have any progress with
> this? We'd love to get the nokia plugin integrated into unity3d-store and
> for that we need it working with the latest version of android-store.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/soomla/android-store/issues/48#issuecomment-90900990>.
>



-- 
Duane Bekaert
218 avenue de Bir Hakeim
FR - 77350 Le Mée-sur-Seine
Tel: +33661790826

"Free software is a matter of liberty, not price." - rms

**Comment by refaelos** [comment]
Sure. Thanks man!
